### ISSUE TITLE
მეტა კლასი გაუწერე მოდელს

### ISSUE THREAD

**Issue by MariamKipshidze** [iraklius9/djangoProject#2]
https://github.com/iraklius9/djangoProject/blob/5b1fe9ec6cf71ba71709631e42e1214e0e05dccc/market/models.py#L4

ძირითადად ვუმატებთ ხოლმე https://docs.djangoproject.com/en/5.0/ref/models/options/#verbose-name
verbose_name და verbose_name_plural ამ პარამეტრებს და მერე საჭიროებისამებრ ბევრი სხვა არის, სტატიაში შეგიძლია ნახო და მერე ჩვენც გავიაროთ ლექციებზე, თუ შეკითხვები გექნება მომწერე

**Comment by iraklius9** [comment]
მარიამ გამარჯობა. მადლობა რჩევებისთვის. ერთი ესეთი პრობლემა შემექმნა. ის
table სადაც წიგნებს ვინახავდი წამეშალა. მერე ვიფიქრე ახალს შევქმნითქო
მაგრამ python manage.py migrations რომ ვუშვებ აერორებს რომ არ არსებობს
table სახელად market_book. რეალურად შემიძლია რეპოზიტორია წამოვიღო თავიდან
და იქ მაქვს ეგ table  მაგრამ საინტერესოა როგორ ხდება მსგავსი პრობლემის
მოგვარება. მადლობა წინასწარ.
